# Generated by Django 6.0.3 on 2026-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Headquarters', 'Amsterdam Office'",
                        max_length=255,
                        verbose_name="Location Name",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Building"
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=255, verbose_name="Street"),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Street Number"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Province/State"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "google_map_url",
                    models.URLField(
                        blank=True,
                        help_text="Embed URL for Google Maps",
                        verbose_name="Google Map URL",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as primary/headquarters location",
                        verbose_name="Primary Location",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RobotsRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        default="*",
                        help_text="User agent pattern (e.g., '*', 'Googlebot', 'GPTBot')",
                        max_length=100,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("allow", "Allow"), ("disallow", "Disallow")],
                        default="disallow",
                        max_length=10,
                        verbose_name="Rule Type",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        default="/",
                        help_text="Path pattern to allow/disallow",
                        max_length=500,
                        verbose_name="Path",
                    ),
                ),
                (
                    "crawl_delay",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Seconds between requests (optional)",
                        null=True,
                        verbose_name="Crawl Delay",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Robots Rule",
                "verbose_name_plural": "Robots Rules",
                "ordering": ["order", "user_agent"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Security Contact Email",
                    ),
                ),
                (
                    "contact_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for security reporting page",
                        verbose_name="Security Contact URL",
                    ),
                ),
                (
                    "encryption_key_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to PGP public key",
                        verbose_name="PGP Key URL",
                    ),
                ),
                (
                    "acknowledgments_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to security researcher acknowledgments",
                        verbose_name="Acknowledgments URL",
                    ),
                ),
                (
                    "policy_url",
                    models.URLField(blank=True, verbose_name="Security Policy URL"),
                ),
                (
                    "hiring_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to security job openings",
                        verbose_name="Security Hiring URL",
                    ),
                ),
                (
                    "preferred_languages",
                    models.CharField(
                        default="en",
                        help_text="Comma-separated language codes",
                        max_length=100,
                        verbose_name="Preferred Languages",
                    ),
                ),
                (
                    "expires_date",
                    models.DateField(
                        blank=True,
                        help_text="When this security.txt expires",
                        null=True,
                        verbose_name="Expires Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Policy",
                "verbose_name_plural": "Security Policy",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_short",
                    models.CharField(
                        blank=True,
                        help_text="Short brand name (e.g., 'Acme')",
                        max_length=100,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "name_long",
                    models.CharField(
                        blank=True,
                        help_text="Full brand name (e.g., 'Acme Corporation')",
                        max_length=255,
                        verbose_name="Long Name",
                    ),
                ),
                (
                    "name_legal",
                    models.CharField(
                        blank=True,
                        help_text="Legal entity name (e.g., 'Acme Corp. Inc.')",
                        max_length=255,
                        verbose_name="Legal Name",
                    ),
                ),
                (
                    "name_abbr",
                    models.CharField(
                        blank=True,
                        help_text="Brand abbreviation (e.g., 'AC')",
                        max_length=20,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="Primary website URL",
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "email_main",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email",
                        max_length=254,
                        verbose_name="Main Email",
                    ),
                ),
                (
                    "email_support",
                    models.EmailField(
                        blank=True,
                        help_text="Support/people email",
                        max_length=254,
                        verbose_name="Support Email",
                    ),
                ),
                (
                    "phone_main",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number",
                        max_length=50,
                        verbose_name="Main Phone",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief site/brand description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO",
                        verbose_name="Keywords",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Full URL to sitemap", verbose_name="Sitemap URL"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Sitemap",
                "verbose_name_plural": "Sitemaps",
            },
        ),
        migrations.CreateModel(
            name="SiteMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="English", max_length=50, verbose_name="Language"
                    ),
                ),
                (
                    "standards",
                    models.TextField(
                        blank=True,
                        default="HTML5, CSS3, JavaScript",
                        help_text="Comma-separated list of standards used",
                        verbose_name="Web Standards",
                    ),
                ),
                (
                    "components",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of frameworks/libraries",
                        verbose_name="Components/Frameworks",
                    ),
                ),
                (
                    "software",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of software used",
                        verbose_name="Software",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g., UA-XXXXXXXX-X or G-XXXXXXXXXX",
                        max_length=50,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "google_search_console_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Google Search Console Token",
                    ),
                ),
                (
                    "google_adsense_id",
                    models.CharField(
                        blank=True,
                        help_text="pub-XXXXXXXXXXXXXXXX",
                        max_length=50,
                        verbose_name="Google AdSense Publisher ID",
                    ),
                ),
                (
                    "ads_txt_content",
                    models.TextField(
                        blank=True,
                        help_text="Custom ads.txt entries",
                        verbose_name="ads.txt Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Metadata",
                "verbose_name_plural": "Site Metadata",
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("500px", "500px"),
                            ("angellist", "AngelList"),
                            ("archinect", "Archinect"),
                            ("behance", "Behance"),
                            ("bluesky", "Bluesky"),
                            ("crunchbase", "Crunchbase"),
                            ("discord", "Discord"),
                            ("dribbble", "Dribbble"),
                            ("facebook", "Facebook"),
                            ("figma", "Figma"),
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("instagram", "Instagram"),
                            ("issuu", "Issuu"),
                            ("linkedin", "LinkedIn"),
                            ("mastodon", "Mastodon"),
                            ("medium", "Medium"),
                            ("pinterest", "Pinterest"),
                            ("reddit", "Reddit"),
                            ("slack", "Slack"),
                            ("snapchat", "Snapchat"),
                            ("spotify", "Spotify"),
                            ("stackoverflow", "Stack Overflow"),
                            ("telegram", "Telegram"),
                            ("threads", "Threads"),
                            ("tiktok", "TikTok"),
                            ("tumblr", "Tumblr"),
                            ("twitch", "Twitch"),
                            ("twitter", "Twitter/X"),
                            ("vimeo", "Vimeo"),
                            ("whatsapp", "WhatsApp"),
                            ("youtube", "YouTube"),
                            ("other", "Other"),
                        ],
                        help_text="Social media platform",
                        max_length=50,
                        verbose_name="Service",
                    ),
                ),
                (
                    "service_custom",
                    models.CharField(
                        blank=True,
                        help_text="If 'Other' selected, specify the service name",
                        max_length=100,
                        verbose_name="Custom Service Name",
                    ),
                ),
                (
                    "profile_url",
                    models.URLField(
                        help_text="Full URL to your profile", verbose_name="Profile URL"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Your username/handle on this platform",
                        max_length=100,
                        verbose_name="Username",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Show this account in templates",
                        verbose_name="Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Account",
                "verbose_name_plural": "Social Accounts",
                "ordering": ["order", "service"],
            },
        ),
        migrations.CreateModel(
            name="WellKnownTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("robots.txt.jinja", "robots.txt"),
                            ("humans.txt.jinja", "humans.txt"),
                            ("security.txt.jinja", "security.txt"),
                            ("ads.txt.jinja", "ads.txt"),
                            ("business.txt.jinja", "business.txt"),
                            ("copyright.txt.jinja", "copyright.txt"),
                            ("license.txt.jinja", "license.txt"),
                            ("hackers.txt.jinja", "hackers.txt"),
                            ("pgp-key.txt.jinja", "pgp-key.txt"),
                            ("trust.txt.jinja", "trust.txt"),
                            ("earth.txt.jinja", "earth.txt"),
                            ("llms.txt.jinja", "llms.txt"),
                            ("ai.txt.jinja", "ai.txt"),
                            ("privacy.txt.jinja", "privacy.txt"),
                            ("dnt-policy.txt.jinja", "dnt-policy.txt"),
                            ("acknowledgments.txt.jinja", "acknowledgments.txt"),
                            ("contact.vcard.jinja", "contact.vcard"),
                            ("contact.ldif.jinja", "contact.ldif"),
                            ("manifest.webmanifest", "manifest.webmanifest"),
                            ("browserconfig.xml", "browserconfig.xml"),
                            ("gpc.json.jinja", "gpc.json"),
                            ("funding.json.jinja", "funding.json"),
                            (
                                "apple-app-site-association.jinja",
                                "apple-app-site-association",
                            ),
                            ("assetlinks.json.jinja", "assetlinks.json"),
                        ],
                        help_text="Select the template to customize",
                        max_length=100,
                        unique=True,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Jinja2 template content. Use {{ variable }} for dynamic content.",
                        verbose_name="Template Content",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Use this custom template instead of the default",
                        verbose_name="Active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this template",
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Well-Known Template",
                "verbose_name_plural": "Well-Known Templates",
                "ordering": ["name"],
            },
        ),
    ]
